# Generated by Django 3.0.3 on 2020-03-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='description',
            field=models.CharField(max_length=800, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
