# Generated by Django 3.0.3 on 2020-03-26 14:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200321_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='message1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
