# Generated by Django 3.0.3 on 2020-03-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_article_message1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='message1',
        ),
    ]
